"""
Answer node LLM functions.

Chain creation and invocation for answer generation.
"""

import logging
import time
from typing import Any, AsyncGenerator

from backend.llm.client import create_chain
from backend.agent.core.config import get_config
from backend.agent.answer.prompts import DATA_ANSWER_TEMPLATE, COMPANY_NOT_FOUND_TEMPLATE


logger = logging.getLogger(__name__)


# Cached chains (lazy initialization)
_answer_chain: Any = None
_not_found_chain: Any = None


def _get_answer_chain() -> Any:
    """Get or create the answer chain."""
    global _answer_chain
    if _answer_chain is None:
        config = get_config()
        _answer_chain = create_chain(
            DATA_ANSWER_TEMPLATE,
            model=config.llm_model,
            temperature=config.llm_temperature,
            max_tokens=config.llm_max_tokens,
        )
        logger.debug("Created answer chain")
    return _answer_chain


def _get_not_found_chain() -> Any:
    """Get or create the not-found chain."""
    global _not_found_chain
    if _not_found_chain is None:
        config = get_config()
        _not_found_chain = create_chain(
            COMPANY_NOT_FOUND_TEMPLATE,
            model=config.llm_model,
            temperature=config.llm_temperature,
            max_tokens=config.llm_max_tokens,
        )
        logger.debug("Created not-found chain")
    return _not_found_chain


def get_answer_chain() -> Any:
    """Get the answer chain for use with LangGraph streaming.

    Returns the LCEL chain directly so LangGraph's astream_events
    can capture on_chat_model_stream events for token streaming.
    """
    return _get_answer_chain()


def build_answer_input(
    question: str,
    conversation_history_section: str,
    company_section: str,
    activities_section: str,
    history_section: str,
    pipeline_section: str,
    renewals_section: str,
    docs_section: str,
    account_context_section: str = "",
    contacts_section: str = "",
    groups_section: str = "",
    attachments_section: str = "",
) -> dict[str, str]:
    """Build input dict for the answer chain."""
    return {
        "question": question,
        "conversation_history_section": conversation_history_section,
        "company_section": company_section,
        "contacts_section": contacts_section,
        "activities_section": activities_section,
        "history_section": history_section,
        "pipeline_section": pipeline_section,
        "renewals_section": renewals_section,
        "groups_section": groups_section,
        "attachments_section": attachments_section,
        "docs_section": docs_section,
        "account_context_section": account_context_section,
    }


def call_answer_chain(
    question: str,
    conversation_history_section: str,
    company_section: str,
    activities_section: str,
    history_section: str,
    pipeline_section: str,
    renewals_section: str,
    docs_section: str,
    account_context_section: str = "",
    contacts_section: str = "",
    groups_section: str = "",
    attachments_section: str = "",
) -> tuple[str, int]:
    """Call the answer chain and return (answer, latency_ms)."""
    chain = _get_answer_chain()
    start_time = time.time()

    answer = chain.invoke({
        "question": question,
        "conversation_history_section": conversation_history_section,
        "company_section": company_section,
        "contacts_section": contacts_section,
        "activities_section": activities_section,
        "history_section": history_section,
        "pipeline_section": pipeline_section,
        "renewals_section": renewals_section,
        "groups_section": groups_section,
        "attachments_section": attachments_section,
        "docs_section": docs_section,
        "account_context_section": account_context_section,
    })

    latency_ms = int((time.time() - start_time) * 1000)
    logger.info(f"Answer chain completed in {latency_ms}ms")
    return answer, latency_ms


async def stream_answer_chain(
    question: str,
    conversation_history_section: str,
    company_section: str,
    activities_section: str,
    history_section: str,
    pipeline_section: str,
    renewals_section: str,
    docs_section: str,
    account_context_section: str = "",
    contacts_section: str = "",
    groups_section: str = "",
    attachments_section: str = "",
) -> AsyncGenerator[str, None]:
    """Stream answer tokens as they're generated by the LLM."""
    chain = _get_answer_chain()

    async for chunk in chain.astream({
        "question": question,
        "conversation_history_section": conversation_history_section,
        "company_section": company_section,
        "contacts_section": contacts_section,
        "activities_section": activities_section,
        "history_section": history_section,
        "pipeline_section": pipeline_section,
        "renewals_section": renewals_section,
        "groups_section": groups_section,
        "attachments_section": attachments_section,
        "docs_section": docs_section,
        "account_context_section": account_context_section,
    }):
        if chunk:
            yield chunk


def call_not_found_chain(question: str, query: str, matches: str) -> tuple[str, int]:
    """Call the not-found chain and return (answer, latency_ms)."""
    chain = _get_not_found_chain()
    start_time = time.time()

    answer = chain.invoke({"question": question, "query": query, "matches": matches})

    latency_ms = int((time.time() - start_time) * 1000)
    logger.info(f"Not-found chain completed in {latency_ms}ms")
    return answer, latency_ms


__all__ = [
    "get_answer_chain",
    "build_answer_input",
    "call_answer_chain",
    "stream_answer_chain",
    "call_not_found_chain",
]
