"""
Answer node LLM functions.

Chain creation and invocation for answer generation.
Loads prompt from prompt.txt for clean separation.
"""

import json
import logging
import time
from collections.abc import AsyncGenerator
from pathlib import Path
from typing import Any

from backend.agent.core.config import get_config
from backend.agent.llm.client import create_chain
from backend.utils.prompt import load_prompt

logger = logging.getLogger(__name__)

DATA_ANSWER_TEMPLATE = load_prompt(Path(__file__).parent / "prompt.txt")


# Cached chain (lazy initialization)
_answer_chain: Any = None


def _get_answer_chain() -> Any:
    """Get or create the answer chain."""
    global _answer_chain
    if _answer_chain is None:
        config = get_config()
        _answer_chain = create_chain(
            DATA_ANSWER_TEMPLATE,
            model=config.llm_model,
            temperature=config.llm_temperature,
            max_tokens=config.llm_max_tokens,
        )
        logger.debug("Created answer chain")
    return _answer_chain


def reset_answer_chain() -> None:
    """Reset the cached answer chain (for testing)."""
    global _answer_chain
    _answer_chain = None


def get_answer_chain() -> Any:
    """Get the answer chain for use with LangGraph streaming.

    Returns the LCEL chain directly so LangGraph's astream_events
    can capture on_chat_model_stream events for token streaming.
    """
    return _get_answer_chain()


def _format_sql_results(sql_results: dict[str, Any] | None) -> str:
    """Format SQL results as JSON string for the LLM prompt."""
    if not sql_results:
        return "(No data retrieved)"

    # Convert to pretty JSON for readability
    try:
        return json.dumps(sql_results, indent=2, default=str)
    except Exception:
        return str(sql_results)


def build_answer_input(
    question: str,
    sql_results: dict[str, Any] | None = None,
    account_context: str = "",
    conversation_history: str = "",
) -> dict[str, str]:
    """Build input dict for the answer chain."""
    # Format conversation history section
    conversation_history_section = ""
    if conversation_history:
        conversation_history_section = f"=== RECENT CONVERSATION ===\n{conversation_history}\n"

    # Format account context section
    account_context_section = ""
    if account_context:
        account_context_section = f"=== ACCOUNT CONTEXT (RAG) ===\n{account_context}\n"

    return {
        "question": question,
        "conversation_history_section": conversation_history_section,
        "sql_results": _format_sql_results(sql_results),
        "account_context_section": account_context_section,
    }


def call_answer_chain(
    question: str,
    sql_results: dict[str, Any] | None = None,
    account_context: str = "",
    conversation_history: str = "",
) -> tuple[str, int]:
    """
    Call the answer chain and return (answer, latency_ms).

    Args:
        question: The user's question
        sql_results: Dict of SQL query results keyed by purpose
        account_context: RAG context from account notes/attachments
        conversation_history: Formatted conversation history

    Returns:
        Tuple of (answer string, latency in ms)
    """
    chain = _get_answer_chain()
    start_time = time.time()

    chain_input = build_answer_input(
        question=question,
        sql_results=sql_results,
        account_context=account_context,
        conversation_history=conversation_history,
    )

    answer = chain.invoke(chain_input)

    latency_ms = int((time.time() - start_time) * 1000)
    logger.info(f"Answer chain completed in {latency_ms}ms")
    return answer, latency_ms


async def stream_answer_chain(
    question: str,
    sql_results: dict[str, Any] | None = None,
    account_context: str = "",
    conversation_history: str = "",
) -> AsyncGenerator[str, None]:
    """
    Stream answer tokens as they're generated by the LLM.

    Args:
        question: The user's question
        sql_results: Dict of SQL query results keyed by purpose
        account_context: RAG context from account notes/attachments
        conversation_history: Formatted conversation history

    Yields:
        Answer tokens as they're generated
    """
    chain = _get_answer_chain()

    chain_input = build_answer_input(
        question=question,
        sql_results=sql_results,
        account_context=account_context,
        conversation_history=conversation_history,
    )

    async for chunk in chain.astream(chain_input):
        if chunk:
            yield chunk


__all__ = [
    "get_answer_chain",
    "reset_answer_chain",
    "build_answer_input",
    "call_answer_chain",
    "stream_answer_chain",
]
